import { Weapon } from '../types/domain';

export const WEAPONS: Weapon[] = [
  // Sidearms
  {
    id: 'classic',
    name: 'Classic',
    category: 'sidearm',
    cost: 0,
    iconPath: '/assets/images/weapon-classic.png',
    selectedIconPath: '/assets/images/weapon-classic-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'shorty',
    name: 'Shorty',
    category: 'sidearm',
    cost: 300,
    iconPath: '/assets/images/weapon-shorty.png',
    selectedIconPath: '/assets/images/weapon-shorty-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'frenzy',
    name: 'Frenzy',
    category: 'sidearm',
    cost: 450,
    iconPath: '/assets/images/weapon-frenzy.png',
    selectedIconPath: '/assets/images/weapon-frenzy-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'ghost',
    name: 'Ghost',
    category: 'sidearm',
    cost: 500,
    iconPath: '/assets/images/weapon-ghost.png',
    selectedIconPath: '/assets/images/weapon-ghost-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'bandit',
    name: 'Bandit',
    category: 'sidearm',
    cost: 600,
    iconPath: '/assets/images/weapon-bandit.png',
    selectedIconPath: '/assets/images/weapon-bandit-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'sheriff',
    name: 'Sheriff',
    category: 'sidearm',
    cost: 800,
    iconPath: '/assets/images/weapon-sheriff.png',
    selectedIconPath: '/assets/images/weapon-sheriff-selected.png',
    enabled: true,
    weight: 1,
  },

  // SMGs
  {
    id: 'stinger',
    name: 'Stinger',
    category: 'smg',
    cost: 1100,
    iconPath: '/assets/images/weapon-stinger.png',
    selectedIconPath: '/assets/images/weapon-stinger-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'spectre',
    name: 'Spectre',
    category: 'smg',
    cost: 1600,
    iconPath: '/assets/images/weapon-spectre.png',
    selectedIconPath: '/assets/images/weapon-spectre-selected.png',
    enabled: true,
    weight: 1,
  },

  // Shotguns
  {
    id: 'bucky',
    name: 'Bucky',
    category: 'shotgun',
    cost: 850,
    iconPath: '/assets/images/weapon-bucky.png',
    selectedIconPath: '/assets/images/weapon-bucky-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'judge',
    name: 'Judge',
    category: 'shotgun',
    cost: 1850,
    iconPath: '/assets/images/weapon-judge.png',
    selectedIconPath: '/assets/images/weapon-judge-selected.png',
    enabled: true,
    weight: 1,
  },

  // Rifles
  {
    id: 'bulldog',
    name: 'Bulldog',
    category: 'rifle',
    cost: 2050,
    iconPath: '/assets/images/weapon-bulldog.png',
    selectedIconPath: '/assets/images/weapon-bulldog-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'guardian',
    name: 'Guardian',
    category: 'rifle',
    cost: 2250,
    iconPath: '/assets/images/weapon-guardian.png',
    selectedIconPath: '/assets/images/weapon-guardian-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'phantom',
    name: 'Phantom',
    category: 'rifle',
    cost: 2900,
    iconPath: '/assets/images/weapon-phantom.png',
    selectedIconPath: '/assets/images/weapon-phantom-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'vandal',
    name: 'Vandal',
    category: 'rifle',
    cost: 2900,
    iconPath: '/assets/images/weapon-vandal.png',
    selectedIconPath: '/assets/images/weapon-vandal-selected.png',
    enabled: true,
    weight: 1,
  },

  // Sniper Rifles
  {
    id: 'marshal',
    name: 'Marshal',
    category: 'sniper',
    cost: 950,
    iconPath: '/assets/images/weapon-marshal.png',
    selectedIconPath: '/assets/images/weapon-marshal-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'outlaw',
    name: 'Outlaw',
    category: 'sniper',
    cost: 2400,
    iconPath: '/assets/images/weapon-outlaw.png',
    selectedIconPath: '/assets/images/weapon-outlaw-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'operator',
    name: 'Operator',
    category: 'sniper',
    cost: 4700,
    iconPath: '/assets/images/weapon-operator.png',
    selectedIconPath: '/assets/images/weapon-operator-selected.png',
    enabled: true,
    weight: 1,
  },

  // Machine Guns
  {
    id: 'ares',
    name: 'Ares',
    category: 'machine_gun',
    cost: 1600,
    iconPath: '/assets/images/weapon-ares.png',
    selectedIconPath: '/assets/images/weapon-ares-selected.png',
    enabled: true,
    weight: 1,
  },
  {
    id: 'odin',
    name: 'Odin',
    category: 'machine_gun',
    cost: 3200,
    iconPath: '/assets/images/weapon-odin.png',
    selectedIconPath: '/assets/images/weapon-odin-selected.png',
    enabled: true,
    weight: 1,
  },

  // Melee
  {
    id: 'melee',
    name: 'Melee',
    category: 'melee',
    cost: 0,
    iconPath: '/assets/images/weapon-knife.png',
    selectedIconPath: '/assets/images/weapon-knife-selected.png',
    enabled: true,
    weight: 1,
  },
];
